/**
 * The editorial plan as data. One entry per slot in the 12-week calendar.
 *
 * Source of truth for the strategy behind every field:
 * editorial/SEARCH-SPEC.md, Parts 2 and 3.
 *
 * Briefs 01 to 30 are fully specified and generate a brief file.
 * Briefs 31 to 48 are calendar rows only, briefed in month two
 * (`brief: false`): they appear in schedule.csv so the slots exist, and get
 * their brief files when Part 3 batch two is written out.
 *
 * Run `node editorial/scripts/generate-briefs.mjs` after editing.
 */

/** Monday of each plan week. Slots run Mon, Tue, Thu, Fri. */
export const WEEK_MONDAYS = {
  1: '2026-09-14',
  2: '2026-09-21',
  3: '2026-09-28',
  4: '2026-10-05',
  5: '2026-10-12',
  6: '2026-10-19',
  7: '2026-10-26',
  8: '2026-11-02',
  9: '2026-11-09',
  10: '2026-11-16',
  11: '2026-11-23',
  12: '2026-11-30',
};

/** Days after the week's Monday, per slot. */
export const SLOT_OFFSET = { A: 0, B: 1, C: 3, D: 4 };

export const SLOT_JOB = {
  A: 'the money page',
  B: 'the spec page',
  C: 'the operations page',
  D: 'the proof page',
};

/** Shared boilerplate every brief repeats, so it stays identical across 30 files. */
export const COMMON = {
  website: 'https://www.hubstudio.ai',
  audience: 'people out of China',
  standingRule:
    'No competitor is ever named, described, compared to, or alluded to. ' +
    'Market figures are attributed to the category and the date, never to a ' +
    'company. Comparison content compares models of buying and regions, ' +
    'never firms.',
};

export const PIECES = [
  // ---------------------------------------------------------------- CLUSTER 1
  {
    id: '01',
    week: 1,
    slot: 'B',
    brief: true,
    status: 'blocked',
    cluster: 'China specs',
    contentType: 'Spec page',
    readerStage: 'practitioner',
    slug: 'tmall-product-image-requirements',
    h1: 'Tmall product image requirements: the complete 2026 spec sheet',
    query: 'tmall product image requirements',
    secondary: [
      'tmall image size',
      'tmall main image dimensions',
      'tmall global image rules',
      'taobao product photo requirements',
    ],
    verdict:
      'VACANT. Top result is a coding tutorial. Only one result mentions Tmall in the body',
    words: 1800,
    angle:
      'The only English page that gives the real numbers, cites the Taobao Rule Center (淘宝规则中心), and separates Tmall domestic from Tmall Global. Every ranking page today is either about a different platform or about code.',
    mustInclude: [
      'Main image count and dimensions',
      'The five slots and what each one is for',
      'Detail page width, mobile against PC',
      'Formats and file weight',
      'Prohibited elements: promotional overlays, superlative claims, watermarks',
      'The three most common rejection reasons, with a screenshot of a real rejection',
      'A category-variation note',
      'A Tmall Global delta table',
    ],
    doNot: [
      'Publish the file size cap or the product fill ratio from a secondary source. Both are on the do-not-publish list in Part 7 of the search spec until a backend capture confirms them.',
    ],
    confidence:
      'State which figures are platform caps and which are performance recommendations. Where sources conflict and backend capture is unavailable, publish the range and say why they conflict.',
    stats: [
      'Main image dimensions and count, from the seller backend or the Taobao Rule Center only',
      'File weight cap, primary capture only, otherwise publish the 500KB against 3MB conflict as a range',
      'Product fill ratio, primary capture only, otherwise publish the 60 percent against 70 to 80 percent conflict as a range',
    ],
    assets: [
      'Spec table: slot, dimensions, format, weight, what it is for',
      'Delta table: Tmall domestic against Tmall Global',
      'Annotated screenshot of the upload screen, seller identifiers blurred',
      'Screenshot of a real rejection notice, account details blurred',
    ],
    links: [
      ['Tmall platform page', '/solutions/platforms/tmall'],
      ['Ecommerce design service', '/services/design/ecommerce'],
      ['China spec library hub', '/resources/specs'],
    ],
    seoTitle: 'Tmall Product Image Requirements 2026',
    seoDesc:
      'The real Tmall image specs: main image dimensions, the five slots, detail page width, file weight, prohibited elements and where Tmall Global differs.',
    faqs: [
      'What size should a Tmall main image be?',
      'How many images can a Tmall listing have?',
      'Why did Tmall reject my product image?',
      'Do Tmall Global listings use different image rules?',
      'Can I reuse my Amazon product images on Tmall?',
    ],
    cta: 'Talk to the production team',
    notes:
      'BLOCKED until the Qianniu (千牛) seller-backend capture session happens. See RUNBOOK, the blocking task. Do not draft a spec table from secondary sources to fill the slot.',
  },
  {
    id: '02',
    week: 3,
    slot: 'B',
    brief: true,
    cluster: 'China specs',
    contentType: 'Spec page',
    readerStage: 'practitioner',
    slug: 'tmall-white-background-image-rules',
    h1: 'The white-background image: the Tmall rule most brands fail',
    query: 'tmall white background image rules',
    secondary: [
      'tmall white background image',
      'baidi tu requirements',
      'tmall search image rules',
    ],
    verdict: 'VACANT. SERP drifts to Amazon and to background-removal tools',
    words: 1400,
    angle:
      'Own the concept. The fifth image is a white-background image (白底图) with its own separate rule set, and no English page explains that it exists, let alone what it does in search and recommendation.',
    mustInclude: [
      'What a white-background image (白底图) is and where it surfaces in search and recommendation',
      'Pure white, RGB 255',
      'No text, watermark, logo, border, shadow or model',
      'Fill ratio guidance with the confidence caveat attached',
      'A before and after',
      'What happens to a listing that fails it',
    ],
    doNot: [
      'State a fill ratio as a hard cap without primary confirmation. Publish the range and the conflict.',
    ],
    stats: [
      'RGB value and prohibited elements, from the platform rule pages only',
      'Fill ratio, primary capture only, otherwise the range',
    ],
    assets: [
      'Before and after pair: a failing image and the corrected version',
      'Table: element, allowed or prohibited, why',
      'Screenshot of where the white-background image surfaces in the app',
    ],
    links: [
      ['Tmall platform page', '/solutions/platforms/tmall'],
      ['AI image production', '/solutions/ai-production/image'],
      ['China spec library hub', '/resources/specs'],
    ],
    seoTitle: 'Tmall White Background Image Rules',
    seoDesc:
      'The white-background image is a separate Tmall requirement with its own rules. What it is, what it forbids, and what fails a listing.',
    faqs: [
      'What is a white-background image on Tmall?',
      'Does the white background have to be pure white?',
      'Can a model appear in a white-background image?',
      'Where does Tmall use the white-background image?',
      'What happens if the white-background image is rejected?',
    ],
    cta: 'Talk to the production team',
  },
  {
    id: '03',
    week: 8,
    slot: 'B',
    brief: true,
    cluster: 'China specs',
    contentType: 'Spec page',
    readerStage: 'practitioner',
    slug: 'tmall-flagship-store-decoration-specs',
    h1: 'Tmall flagship store decoration specs, module by module',
    query: 'tmall flagship store banner size specifications',
    secondary: [
      'tmall store decoration size',
      'tmall shop banner dimensions',
      'tmall store module specs',
    ],
    verdict: 'VACANT. A physical signage vendor ranks in the top five',
    words: 1700,
    angle:
      'A real module-by-module spec sheet, PC against mobile, that a designer can build from without opening the backend.',
    mustInclude: [
      'Header and banner dimensions',
      'Floor module sizes',
      'Navigation',
      'Live tab',
      'The mobile-first reality of Tmall traffic',
      'How a 618 (六一八) or Singles Day (双十一) skin differs from an always-on store',
      'An asset checklist for a full store refresh',
    ],
    stats: [
      'Module dimensions, from the store decoration backend only',
      'Mobile share of Tmall traffic, category source with a date and a method',
    ],
    assets: [
      'Spec table: module, PC size, mobile size, notes',
      'Annotated screenshot of the decoration backend',
      'Checklist: every asset a full store refresh needs',
    ],
    links: [
      ['Tmall platform page', '/solutions/platforms/tmall'],
      ['Brands solutions page', '/solutions/brands'],
      ['China spec library hub', '/resources/specs'],
    ],
    seoTitle: 'Tmall Flagship Store Decoration Specs',
    seoDesc:
      'Module-by-module Tmall store specs, PC and mobile: header, banners, floor modules, navigation, live tab, plus a full refresh asset checklist.',
    faqs: [
      'What size is a Tmall store banner?',
      'Do Tmall store modules differ between mobile and PC?',
      'How many assets does a Tmall store refresh need?',
      'How does a Singles Day store skin differ from an always-on store?',
      'Can one design serve both the store and the listing pages?',
    ],
    cta: 'Talk to the production team',
  },
  {
    id: '04',
    week: 4,
    slot: 'B',
    brief: true,
    cluster: 'China specs',
    contentType: 'Spec page',
    readerStage: 'practitioner',
    slug: 'jd-image-requirements-vs-tmall',
    h1: 'JD image requirements, and the twelve places they differ from Tmall',
    query: 'jd.com product image requirements',
    secondary: [
      'jd image size',
      'jingdong product image specs',
      'jd vs tmall image requirements',
    ],
    verdict:
      'VACANT. Two of five results are about a different company that shares the initials',
    words: 1700,
    angle:
      'The delta table nobody has published. A brand selling on both is producing two sets of assets and mostly does not know which parts actually differ.',
    mustInclude: [
      'JD (京东) main image rules',
      'Detail page',
      'JD ad slot ratios (Jingzhuntong, Kuaiche)',
      'A side-by-side Tmall against JD table with a "same or different" column',
      'What has to be reshot against what can be re-cropped',
    ],
    stats: [
      'JD main image and detail page dimensions, from the JD seller backend only',
      'Ad slot ratios, from the JD ad platform documentation only',
    ],
    assets: [
      'Delta table: spec, Tmall, JD, same or different',
      'Table: reshoot against re-crop, by asset type',
      'Annotated screenshot of the JD upload screen',
    ],
    links: [
      ['JD platform page', '/solutions/platforms/jd'],
      ['Ecommerce design service', '/services/design/ecommerce'],
      ['China spec library hub', '/resources/specs'],
    ],
    seoTitle: 'JD Image Requirements vs Tmall',
    seoDesc:
      'JD main image, detail page and ad slot specs, with a side-by-side Tmall delta table showing what has to be reshot and what can be re-cropped.',
    faqs: [
      'What size should a JD main image be?',
      'Are JD and Tmall image requirements the same?',
      'What are the JD ad slot image ratios?',
      'Can I reuse Tmall images on JD?',
      'Which assets have to be reshot for JD?',
    ],
    cta: 'Talk to the production team',
  },
  {
    id: '05',
    week: 2,
    slot: 'B',
    brief: true,
    cluster: 'China specs',
    contentType: 'Spec page',
    readerStage: 'practitioner',
    slug: 'douyin-video-specs-safe-zones',
    h1: 'Douyin video specs and safe zones: why a TikTok cut fails',
    query: 'douyin video specifications aspect ratio safe zone',
    secondary: [
      'douyin video size',
      'douyin safe zone',
      'douyin aspect ratio',
      'douyin video specs 2026',
    ],
    verdict: 'VACANT. Every top result is about TikTok',
    words: 1900,
    angle:
      'State plainly that Douyin (抖音) is not TikTok in UI overlay geometry, and publish an annotated safe-zone diagram with pixel offsets. The whole SERP answers a Douyin query with TikTok numbers.',
    mustInclude: [
      'Resolution, aspect ratio, duration bands, codec, bitrate, file size',
      'The UI overlay map with top, bottom, right-rail and caption zones measured',
      'Where a TikTok master\'s captions and end cards land on Douyin',
      'Cover frame requirements',
      'Sound-on assumptions',
      'A re-export fix checklist',
    ],
    stats: [
      'Overlay offsets, measured from live app captures at a stated device and resolution',
      'Codec, bitrate and file size caps, from the Douyin creator or Ocean Engine (巨量引擎) documentation only',
    ],
    assets: [
      'Annotated safe-zone diagram with pixel offsets, device and resolution stated',
      'Spec table: field, value, source surface',
      'Side-by-side: the same master on TikTok and on Douyin, overlays shown',
      'Re-export checklist',
    ],
    links: [
      ['Douyin platform page', '/solutions/platforms/douyin'],
      ['Short video design service', '/services/design/short-video'],
      ['China spec library hub', '/resources/specs'],
    ],
    seoTitle: 'Douyin Video Specs and Safe Zones',
    seoDesc:
      'Douyin is not TikTok. Resolution, duration, codec and an annotated safe-zone map with pixel offsets, plus a re-export checklist for TikTok masters.',
    faqs: [
      'What is the Douyin safe zone?',
      'Can I upload a TikTok video to Douyin?',
      'What aspect ratio does Douyin use?',
      'How long can a Douyin video be?',
      'Where do Douyin captions and end cards get covered?',
    ],
    cta: 'Talk to the production team',
  },
  {
    id: '06',
    week: 6,
    slot: 'B',
    brief: true,
    cluster: 'China specs',
    contentType: 'Spec page',
    readerStage: 'practitioner',
    slug: 'douyin-ad-creative-specs-by-format',
    h1: 'Douyin ad creative specs by format: TopView, in-feed, open screen',
    query: 'douyin ad creative specs 2026',
    secondary: [
      'douyin topview specs',
      'douyin in-feed ad size',
      'ocean engine creative specs',
    ],
    verdict:
      'WEAK. The ranking pages cover ad types and costs, never dimensions',
    words: 1800,
    angle:
      'The creative spec sheet per format, sourced to Ocean Engine (巨量引擎), with a visible reviewed date. The incumbents answer a specs query with a media-buying article.',
    mustInclude: [
      'One table per placement covering dimensions, duration, file weight, title and copy limits, landing behavior',
      'What gets rejected and why',
      'The production implication of each format: open screen needs a first-frame hero, in-feed needs a hook inside 1.5 seconds',
    ],
    stats: [
      'Per-placement dimensions, duration and weight, from Ocean Engine documentation only',
      'Copy character limits, from the ad backend only',
    ],
    assets: [
      'One spec table per placement',
      'Table: rejection reason, what triggers it, the fix',
      'Annotated screenshot of the Ocean Engine creative upload screen',
    ],
    links: [
      ['Douyin platform page', '/solutions/platforms/douyin'],
      ['Ad creative design service', '/services/design/ad-creative'],
      ['China spec library hub', '/resources/specs'],
    ],
    seoTitle: 'Douyin Ad Creative Specs by Format',
    seoDesc:
      'Douyin ad specs per placement: TopView, in-feed and open screen dimensions, duration, file weight, copy limits and what gets creative rejected.',
    faqs: [
      'What are the Douyin TopView creative specs?',
      'What size is a Douyin in-feed ad?',
      'What are the open screen ad requirements?',
      'Why was my Douyin ad creative rejected?',
      'How long can a Douyin ad video be?',
    ],
    cta: 'Talk to the production team',
  },
  {
    id: '07',
    week: 5,
    slot: 'B',
    brief: true,
    cluster: 'China specs',
    contentType: 'Spec page',
    readerStage: 'practitioner',
    slug: 'rednote-note-cover-specs',
    h1: 'RedNote note and cover specs, verified against the live app',
    query: 'xiaohongshu image size note cover dimensions',
    secondary: [
      'rednote image size',
      'xiaohongshu cover size',
      'xiaohongshu note dimensions',
      'rednote video specs',
    ],
    verdict:
      'CONTESTED. Several tool sites give 3:4 and 1080x1440, all uncited, one claiming verification against official docs while linking to none',
    words: 1600,
    angle:
      'The only version with screenshots from the live app and a maintained changelog. Win on proof, not on being first.',
    mustInclude: [
      'Note image ratios and counts',
      'Cover crop behavior in feed against profile grid',
      'Video note specs',
      'Text safe areas',
      'How the cover is cropped differently in search',
      'A dated changelog block at the foot',
    ],
    stats: [
      'Ratios and crop behavior, measured from live app captures with the app version and capture date stated',
    ],
    assets: [
      'Spec table: surface, ratio, pixel size, crop behavior',
      'Live app screenshots: feed, profile grid, search, with the crop lines drawn on',
      'Changelog block, dated, updated in place',
    ],
    links: [
      ['RedNote platform page', '/solutions/platforms/rednote'],
      ['Social media design service', '/services/design/social-media'],
      ['China spec library hub', '/resources/specs'],
    ],
    seoTitle: 'RedNote Note and Cover Specs 2026',
    seoDesc:
      'RedNote image ratios, cover crops in feed, profile and search, video note specs and text safe areas, verified against the live app with a changelog.',
    faqs: [
      'What size should a RedNote cover image be?',
      'What aspect ratio does RedNote use?',
      'Why is my RedNote cover cropped differently in search?',
      'How many images can a RedNote note have?',
      'What are the RedNote video note specs?',
    ],
    cta: 'Talk to the production team',
  },
  {
    id: '08',
    week: 7,
    slot: 'B',
    brief: true,
    cluster: 'China specs',
    contentType: 'Spec page',
    readerStage: 'practitioner',
    slug: 'wechat-specs-articles-channels-mini-program',
    h1: 'WeChat specs in one place: articles, Channels, Mini Program',
    query: 'wechat official account article image size specs',
    secondary: [
      'wechat channels video specs',
      'wechat mini program banner size',
      'wechat article cover size',
    ],
    verdict:
      'WEAK. The canonical incumbent is from 2022 and a 2019 PDF also ranks',
    words: 2000,
    angle:
      'Pure recency plus consolidation. Three surfaces, one maintained page, dated. The pages holding this query were written before two of the three surfaces looked the way they look now.',
    mustInclude: [
      'Official Account article header and inline image sizes',
      'Cover thumbnail crops for the different card layouts',
      'WeChat Channels (视频号) video specs, and how a Channels cut differs from a Douyin (抖音) cut of the same shoot',
      'Mini Program banner and card sizes',
      'Tencent Ads placements',
    ],
    stats: [
      'Article, Channels and Mini Program dimensions, from the WeChat backend and official documentation only',
    ],
    assets: [
      'One spec table per surface',
      'Table: Channels cut against Douyin cut, same shoot',
      'Annotated screenshots of the article editor and the Channels upload screen',
    ],
    links: [
      ['WeChat platform page', '/solutions/platforms/wechat'],
      ['Social media design service', '/services/design/social-media'],
      ['China spec library hub', '/resources/specs'],
    ],
    seoTitle: 'WeChat Specs: Articles, Channels, Mini App',
    seoDesc:
      'WeChat image and video specs in one maintained page: Official Account articles, cover crops, Channels video, Mini Program banners and Tencent Ads.',
    faqs: [
      'What size is a WeChat article cover image?',
      'What are the WeChat Channels video specs?',
      'Can I reuse a Douyin cut on WeChat Channels?',
      'What size are Mini Program banners?',
      'What image sizes work inside a WeChat article body?',
    ],
    cta: 'Talk to the production team',
  },
  {
    id: '09',
    week: 8,
    slot: 'D',
    brief: true,
    cluster: 'China specs',
    contentType: 'Spec page',
    readerStage: 'practitioner',
    slug: 'weibo-image-video-specs',
    h1: 'Weibo image and video specs for brands, updated for 2026',
    query: 'weibo image and video specs',
    secondary: [
      'weibo image size',
      'weibo video specs',
      'weibo nine grid',
      'weibo ad specs',
    ],
    verdict:
      'WEAK. One real answer from 2022, plus a brand-logo library and three encyclopaedia entries',
    words: 1300,
    angle:
      'The easiest single win in the set. No live competition at all, so the job is simply to be current, complete and dated.',
    mustInclude: [
      'Post image counts and crops',
      'Nine-grid behavior',
      'Video specs',
      'Cover images',
      'Weibo (微博) ad placements',
      'What changed since the 2022 guides that still rank',
    ],
    stats: [
      'Dimensions and crop behavior, from the Weibo backend and live app captures only',
    ],
    assets: [
      'Spec table: surface, count, ratio, crop',
      'Nine-grid crop diagram',
      'Table: what changed since 2022',
    ],
    links: [
      ['Weibo platform page', '/solutions/platforms/weibo'],
      ['Social media design service', '/services/design/social-media'],
      ['China spec library hub', '/resources/specs'],
    ],
    seoTitle: 'Weibo Image and Video Specs 2026',
    seoDesc:
      'Current Weibo specs for brands: post image counts and crops, nine-grid behavior, video and cover sizes, ad placements, and what changed since 2022.',
    faqs: [
      'What size should a Weibo post image be?',
      'How does the Weibo nine-grid crop images?',
      'What are the Weibo video specs?',
      'What changed in Weibo specs since 2022?',
      'What are the Weibo ad placement sizes?',
    ],
    cta: 'Talk to the production team',
  },
  {
    id: '10',
    week: 2,
    slot: 'D',
    brief: true,
    cluster: 'China specs',
    contentType: 'Linkable asset',
    readerStage: 'practitioner',
    slug: 'one-shoot-six-platforms-china-variant-matrix',
    h1: 'One shoot, six platforms: the China variant matrix',
    query: 'china social media creative asset variants',
    secondary: [
      'china platform asset matrix',
      'how many assets for china launch',
      'china creative variants per sku',
    ],
    verdict:
      'VACANT. Every result is a "top China platforms" listicle. Low search volume, high link value. A linkable asset, not a traffic play',
    words: 1600,
    angle:
      'Publish the actual matrix. One product shoot, six platforms, N ratios, M copy lengths, and the real asset count that comes out the other end. Everyone quotes "we adapt for every platform" and nobody has published what that number is.',
    mustInclude: [
      'The matrix as one wide table, platform down, asset type across',
      'The total asset count for a single SKU launch',
      'Which cells are re-crops, which are re-edits, which need new capture',
      'What you must capture on the shoot day to serve all six',
    ],
    stats: [
      'Every cell in the matrix traces to the corresponding spec piece in the cluster. Nothing enters this table that is not already verified on a spec page.',
      'The total asset count is derived arithmetic from the matrix, labeled as such, not a survey figure',
    ],
    assets: [
      'The matrix, one wide table, five columns maximum, split across two tables if needed',
      'Table: cell type, re-crop, re-edit or new capture',
      'Shoot-day capture checklist',
    ],
    links: [
      ['Solutions overview', '/solutions'],
      ['AI image production', '/solutions/ai-production/image'],
      ['DIY European retailer case study', '/work/diy-european-retailer'],
    ],
    seoTitle: 'One Shoot, Six Platforms: China Matrix',
    seoDesc:
      'One product shoot across six Chinese platforms: the full variant matrix, the real asset count per SKU, and what to capture on the day to serve all six.',
    faqs: [
      'How many assets does one SKU need for China?',
      'Can one shoot serve Tmall, JD, Douyin and RedNote?',
      'Which China assets are re-crops and which need new capture?',
      'What has to be captured on the shoot day?',
      'How many aspect ratios does a China launch need?',
    ],
    cta: 'Talk to the production team',
  },

  // ---------------------------------------------------------------- CLUSTER 2
  {
    id: '11',
    week: 2,
    slot: 'A',
    brief: true,
    flagship: true,
    cluster: 'Cost',
    contentType: 'Money page',
    readerStage: 'budget-holder',
    slug: 'what-a-finished-brand-asset-costs',
    h1: 'What a finished brand asset actually costs in 2026',
    query: 'cost per creative asset benchmark',
    secondary: [
      'cost per asset creative production',
      'brand content cost per asset',
      'creative production cost benchmark 2026',
      'how much does one ad creative cost',
    ],
    verdict:
      'VACANT. No production company, trade body or consultancy publishes a usable answer',
    words: 3200,
    angle:
      'The first page that answers the question with absolute figures, a stated method, no email gate, and a clear definition of what one unit is. The absence is structural: agencies will not disclose unit cost because it exposes margin, software vendors publish only figures that flatter their pricing, and consultancies gate. The position is open to anyone willing to publish absolute numbers with a stated method.',
    mustInclude: [
      'A definition of "one finished asset" before any number appears',
      'Cost bands by asset type: static PDP image, lifestyle image, 15-second social cut, 30-second brand film, campaign adaptation',
      'What is inside each band: direction, capture, retouch, versioning, clearance, project management',
      'The four buying models compared as models, not firms: freelance, agency retainer, subscription, offshore studio, with published category price ranges and the date they were collected',
      'Why the existing benchmarks fail as a category: savings percentages instead of absolutes, no sample size, vendor-published, or measuring volume rather than cost, with no company named',
      'A methodology box',
    ],
    doNot: [
      'Publish a hubStudio rate. Send that to the calculator.',
      'Name the company behind any benchmark being criticised. The critique works on the category pattern.',
    ],
    stats: [
      'Managed design subscription monthly floors, category range, collection date stated',
      'Ecommerce retouch per-image floor, category range, collection date stated',
      'Every band carries its own method sentence: what is counted, what is excluded, over what sample',
    ],
    assets: [
      'Answer table in the first screen: asset type, cost band, what is inside it',
      'Table: the four buying models, what you buy, published category range, date collected',
      'Methodology box: definition of a unit, what is counted, sample, collection dates',
    ],
    links: [
      ['Pricing page', '/pricing'],
      ['Quotation calculator', '/pricing/calculator'],
      ['AI excellence page', '/the-studio/ai-excellence'],
    ],
    seoTitle: 'What a Brand Asset Costs in 2026',
    seoDesc:
      'Absolute cost bands per finished brand asset, with the method stated and no email gate: images, social cuts, brand films and campaign adaptations.',
    faqs: [
      'How much does one creative asset cost?',
      'What counts as one finished asset?',
      'How much does a 30-second brand film cost?',
      'Why do agencies not publish cost per asset?',
      'Is a subscription cheaper than a production studio?',
      'What does a cost per asset figure usually leave out?',
    ],
    cta: 'Get a market range for your volume',
    notes:
      'The flagship of the cost cluster. Widest research pass in the plan. Start it in week 1.',
  },
  {
    id: '12',
    week: 6,
    slot: 'A',
    brief: true,
    cluster: 'Cost',
    contentType: 'Money page',
    readerStage: 'budget-holder',
    slug: 'product-photography-cost-per-sku',
    h1: 'Product photography cost per SKU, from 50 SKUs to 5,000',
    query: 'how much does ecommerce product photography cost per SKU',
    secondary: [
      'product photography cost per sku',
      'ecommerce photography pricing volume',
      'bulk product photography cost',
    ],
    verdict:
      'WEAK at volume. Head term crowded with single-photographer day-rate framing',
    words: 2800,
    angle:
      'Own the volume tier nobody covers. A real per-SKU cost curve with the breakpoints where studio capture plus generated extension beats pure photography. Day-rate framing falls apart above about 200 SKUs and nobody says so.',
    mustInclude: [
      'The curve as a table at 50, 200, 500, 2,000 and 5,000 SKUs',
      'Fixed against variable cost split',
      'What a day rate hides at volume: styling, sample logistics, reshoots, retouch queue',
      'The 70/30 generated-to-shot mix and where that ratio moves',
      'The published per-image retouch floor in the market, quoted as a category range, with the point that retouch is not production',
    ],
    doNot: ['Publish a hubStudio per-SKU rate. Send that to the calculator.'],
    stats: [
      'Per-SKU cost curve, absolute figures, method and sample stated for each tier',
      'Retouch per-image floor, category range with a collection date',
      'The 70/30 mix is hubStudio delivery data: state the method and the period on the page',
    ],
    assets: [
      'Cost curve table: 50, 200, 500, 2,000, 5,000 SKUs',
      'Table: fixed against variable, by cost line',
      'Chart: cost per SKU against volume, showing the breakpoint',
    ],
    links: [
      ['Ecommerce design service', '/services/design/ecommerce'],
      ['Retailers solutions page', '/solutions/retailers'],
      ['Quotation calculator', '/pricing/calculator'],
    ],
    seoTitle: 'Product Photography Cost per SKU',
    seoDesc:
      'A real per-SKU cost curve from 50 to 5,000 SKUs, what a day rate hides at volume, and where studio capture plus generation beats pure photography.',
    faqs: [
      'How much does product photography cost per SKU?',
      'Does cost per SKU fall at volume?',
      'What does a photography day rate not cover?',
      'When is generation cheaper than shooting?',
      'How much does ecommerce retouching cost per image?',
    ],
    cta: 'Get a market range for your catalog',
  },
  {
    id: '13',
    week: 4,
    slot: 'A',
    brief: true,
    cluster: 'Cost',
    contentType: 'Money page',
    readerStage: 'budget-holder',
    slug: 'cost-to-localize-a-campaign-for-china',
    h1: 'What it costs to localize a global campaign for China',
    query: 'cost to localize a global campaign for China',
    secondary: [
      'china campaign localization cost',
      'adapt global campaign for china',
      'china market campaign adaptation budget',
    ],
    verdict:
      'VACANT for the production reading. SERP is translation SaaS and game-localization vendors',
    words: 3000,
    angle:
      'Localizing for China is a re-shoot and re-layout problem, not a translation problem. Software cannot fake a stage. Every page holding this query prices words.',
    mustInclude: [
      'The cost stack: adaptation, re-shoot, model recasting, platform variants, copy transcreation, compliance and labeling, upload QA',
      'Why a Western master usually cannot be re-cropped',
      'The asset count from the China variant matrix as the multiplier',
      'What a translation quote leaves out, itemised',
      'Two worked examples at different budget levels',
    ],
    doNot: ['Publish a hubStudio rate. Send that to the calculator.'],
    stats: [
      'Each cost line carries a category range with a collection date, or is labeled as a structural cost with no published benchmark',
      'The asset count multiplier comes from the China variant matrix piece, cited by name',
    ],
    assets: [
      'Answer table in the first screen: cost line, what it covers, category range',
      'Table: what a translation quote includes against what a production quote includes',
      'Two worked examples, itemised',
    ],
    links: [
      ['Brands solutions page', '/solutions/brands'],
      ['Tmall platform page', '/solutions/platforms/tmall'],
      ['Premium SUV case study', '/work/premium-suv'],
    ],
    seoTitle: 'Cost to Localize a Campaign for China',
    seoDesc:
      'China localization is a re-shoot and re-layout problem, not a translation one. The full cost stack, what a translation quote leaves out, two examples.',
    faqs: [
      'How much does it cost to adapt a campaign for China?',
      'Is China localization just translation?',
      'Why can a Western master not be re-cropped for China?',
      'What does a translation quote leave out?',
      'How many assets does a China adaptation produce?',
    ],
    cta: 'Get a market range for your campaign',
    notes: 'Most defensible query in the set.',
  },
  {
    id: '14',
    week: 7,
    slot: 'A',
    brief: true,
    cluster: 'Cost',
    contentType: 'Money page',
    readerStage: 'budget-holder',
    slug: 'all-in-cost-of-ai-video',
    h1: 'The all-in cost of AI video, and what the dollar-an-ad math leaves out',
    query: 'AI video production cost for brands',
    secondary: [
      'ai video ad cost',
      'cost of ai generated video',
      'ai video production pricing',
    ],
    verdict:
      'CONTESTED, but the ranking pages are conflicted: software vendors understate cost to sell seats',
    words: 2700,
    angle:
      'The honest all-in figure, including the shot plates, direction, retakes, clearance and versioning that tool-side estimates leave out. A studio can publish this because it does not sell seats.',
    mustInclude: [
      'A line-by-line build of a real 30-second AI-assisted brand film',
      'Generation cost against total cost as a ratio',
      'The retake and selection rate nobody publishes',
      'Rights clearance and talent releases as a cost line',
      'The circulating dollar-to-five-dollars per AI ad figure quoted as a market claim and then unpacked',
      'Where AI genuinely does cost a fraction, with the conditions attached',
    ],
    doNot: [
      'Publish a hubStudio rate.',
      'Name any AI video tool vendor, or characterise a specific one as understating cost. The pattern is the point.',
    ],
    stats: [
      'The dollar-to-five-dollars per ad figure is a circulating market claim: label it as a claim, then unpack what it excludes',
      'Retake and selection rate is hubStudio delivery data: state the method, the sample and the period',
      'Generation cost against total cost, as a ratio with the build shown',
    ],
    assets: [
      'Line-by-line build table for one 30-second film',
      'Table: what a tool-side estimate counts against what a delivered film costs',
      'Chart: generation cost as a share of total cost',
    ],
    links: [
      ['AI video production', '/solutions/ai-production/video'],
      ['Video production service', '/services/design/video-production'],
      ['Quotation calculator', '/pricing/calculator'],
    ],
    seoTitle: 'The All-In Cost of AI Video',
    seoDesc:
      'A line-by-line build of a 30-second AI-assisted brand film: what generation actually costs, and what the dollar-an-ad math leaves out.',
    faqs: [
      'How much does an AI video ad cost?',
      'Is AI video really a dollar per ad?',
      'What does AI video generation not cover?',
      'How many generations does one usable shot take?',
      'When is AI video genuinely cheaper?',
    ],
    cta: 'Get a market range for your video program',
  },
  {
    id: '15',
    week: 8,
    slot: 'A',
    brief: true,
    cluster: 'Cost',
    contentType: 'Money page',
    readerStage: 'budget-holder',
    slug: 'in-house-studio-vs-outsourced-production',
    h1: 'In-house studio or outsourced production: the fully loaded model',
    query: 'in-house creative studio cost vs outsourcing',
    secondary: [
      'in-house agency cost model',
      'in-house studio vs agency cost',
      'cost of running an in-house creative team',
    ],
    verdict:
      'WEAK. Heavily written about, thinly evidenced, nobody publishes a loaded model',
    words: 2900,
    angle:
      'The costs in-house teams never book. Recruitment, idle capacity between campaigns, software seats, freelancer surge, and the share of headcount absorbed by trafficking and versioning rather than making anything.',
    mustInclude: [
      'A fully loaded annual model with every line named',
      'The utilization question: what share of a salaried creative\'s year is on billable output',
      'The fixed against variable argument',
      'When in-house is genuinely right',
      'The hybrid model, platform plus studio, as the third option',
      'ANA data showing 82 percent of members run an in-house agency, up from 78 percent in 2018',
    ],
    doNot: ['Publish a hubStudio rate.'],
    stats: [
      'ANA in-house agency share, 82 percent, up from 78 percent in 2018, with the survey date and population stated',
      'Every line in the loaded model carries a category range and a collection date, or is labeled structural',
    ],
    assets: [
      'Fully loaded annual model, one table, every line named',
      'Decision table: volume, variation, originated against adapted, which model fits',
      'Chart: cost per asset against utilization rate',
    ],
    links: [
      ['hub4you platform', '/hub4you'],
      ['Consulting solutions page', '/solutions/consulting'],
      ['Quotation calculator', '/pricing/calculator'],
    ],
    seoTitle: 'In-House Studio or Outsourced Production',
    seoDesc:
      'The fully loaded annual model for an in-house creative studio, the costs nobody books, the utilization question, and when in-house is genuinely right.',
    faqs: [
      'Is an in-house studio cheaper than outsourcing?',
      'What does a fully loaded in-house model include?',
      'What utilization rate does an in-house team actually hit?',
      'When does in-house production make sense?',
      'What is the hybrid platform and studio model?',
    ],
    cta: 'Model it against your volume',
  },
  {
    id: '16',
    week: 8,
    slot: 'C',
    brief: true,
    cluster: 'Cost',
    contentType: 'Money page',
    readerStage: 'budget-holder',
    slug: 'campaign-adaptation-cost-per-market',
    h1: 'Campaign adaptation cost: pricing one master across N markets',
    query: 'campaign adaptation cost per market',
    secondary: [
      'toolkit adaptation cost',
      'campaign versioning cost per market',
      'master and adapt production cost',
    ],
    verdict:
      'VACANT, and the query does not resolve: search returns media budget articles. Define the category',
    words: 2500,
    angle:
      'Name the unit. One master, N markets, M formats, so a global brand can budget a toolkit rollout instead of guessing. The query does not resolve because the category has no agreed vocabulary yet.',
    mustInclude: [
      'The unit definition',
      'A rate structure by format family',
      'Where cost scales linearly with markets and where it does not',
      'Language, legal and platform variables',
      'A worked toolkit example at 12 markets',
      'The vocabulary buyers actually use: versioning, toolkit adaptation, master and adapt, so the page catches the real phrasings',
    ],
    doNot: ['Publish a hubStudio rate.'],
    stats: [
      'Each format family carries a category range with a collection date',
      'The linear against non-linear breakpoint is derived arithmetic, shown, not asserted',
    ],
    assets: [
      'Answer table: format family, unit, what scales, what does not',
      'Worked example: one master, 12 markets, itemised',
      'Glossary table: the phrasings buyers use for the same thing',
    ],
    links: [
      ['Pricing page', '/pricing'],
      ['Agencies solutions page', '/solutions/agencies'],
      ['Quotation calculator', '/pricing/calculator'],
    ],
    seoTitle: 'Campaign Adaptation Cost per Market',
    seoDesc:
      'One master, N markets, M formats. The unit definition, a rate structure by format family, and where adaptation cost stops scaling linearly.',
    faqs: [
      'How much does campaign adaptation cost per market?',
      'What is a toolkit adaptation?',
      'Does adaptation cost scale linearly with markets?',
      'What drives adaptation cost up?',
      'What is the difference between versioning and adaptation?',
    ],
    cta: 'Get a market range for your rollout',
  },

  // ---------------------------------------------------------------- CLUSTER 3
  {
    id: '17',
    week: 1,
    slot: 'A',
    brief: true,
    cluster: 'Buying models',
    contentType: 'Money page',
    readerStage: 'procurement',
    slug: 'production-roster-review-questions',
    h1: 'Your production roster is consolidating. The 14 questions to ask now',
    query: 'production agency roster review checklist',
    secondary: [
      'production partner review questions',
      'creative roster consolidation',
      'production agency review checklist',
    ],
    verdict:
      'WEAK. Trade news covers the industry shift, nobody has written the buyer\'s instrument',
    words: 2800,
    angle:
      'Production has moved from a network-distributed model, where each agency ran its own studio, to centralized units attached to platforms. That is an industry fact, stated without naming anyone. Consolidation triggers roster reviews, and roster reviews are when production budgets move. Be the instrument that runs the review.',
    mustInclude: [
      'What centralization changes in practice: who your producer reports to, what tooling your assets pass through, how utilization drives pricing',
      'The 14 questions in four groups: contract continuity, commercials, bidding conflict, platform and data exit',
      'A copyable scoring table',
      'The ANA 2017 production transparency findings',
      'The point that the questions apply to every partner on the roster, including hubStudio',
    ],
    doNot: [
      'Name any holding company, production unit, rebrand, executive, financial result or website. The piece works on the pattern, not on an example.',
    ],
    stats: [
      'ANA 2017 production transparency study: fewer than half of respondents required in-house bidding disclosure, over 60 percent did not require production rebates returned. Survey date and population stated.',
      'The centralization shift is described as a category pattern with no company named and no figure attached unless one can be sourced to a trade body',
    ],
    assets: [
      'The 14 questions, grouped, each with what a good answer sounds like and what a weak one sounds like',
      'Copyable scoring table, one row per question, three vendor columns',
      'Table: what centralization changes, before and after',
    ],
    links: [
      ['Brands solutions page', '/solutions/brands'],
      ['Work index', '/work'],
      ['Pricing page', '/pricing'],
    ],
    seoTitle: '14 Questions for a Production Roster Review',
    seoDesc:
      'Production is consolidating into centralized units. The 14 questions to ask every partner on your roster, grouped, with a copyable scoring table.',
    faqs: [
      'What is a production roster review?',
      'What changes when production consolidates?',
      'What should I ask a production partner about bidding conflict?',
      'How do I score production vendors consistently?',
      'What is a production rebate?',
      'Who owns my assets if I leave a production platform?',
    ],
    cta: 'Book a roster review call',
    notes:
      'Publish first. An earlier draft of this piece was built around a named company. It is void. Rewrite from this brief.',
  },
  {
    id: '18',
    week: 3,
    slot: 'A',
    brief: true,
    cluster: 'Buying models',
    contentType: 'Money page',
    readerStage: 'budget-holder',
    slug: 'automation-platform-or-production-partner',
    h1: 'Automation multiplies, studios originate: platform or production partner',
    query: 'creative automation platform vs production studio',
    secondary: [
      'creative automation vs agency',
      'creative automation platform limits',
      'who makes the master creative',
    ],
    verdict:
      'VACANT. Every ranking result is a software vendor comparing itself to other software vendors. The studio half of the query is unanswered',
    words: 3000,
    angle:
      'The argument no software vendor can make. Automation multiplies assets you already have. It cannot originate the master. So the real question is who makes the master, and at what cost.',
    mustInclude: [
      'What each layer genuinely does well, described as layers rather than products',
      'The handoff point between studio and platform',
      'Why the two are complementary, since the buyer usually already owns the stack',
      'A cost comparison of the two layers',
      'A decision table on volume, variation count, and how much of the work is originated against adapted',
    ],
    doNot: ['Name any automation platform.'],
    stats: [
      'Layer costs carry category ranges with collection dates',
      'The originated against adapted ratio is described structurally unless a sourced figure exists',
    ],
    assets: [
      'Layer diagram: originate, multiply, distribute, with the handoff marked',
      'Decision table: volume, variation count, originated share, which layer',
      'Cost comparison table, two layers',
    ],
    links: [
      ['hub4you platform', '/hub4you'],
      ['AI excellence page', '/the-studio/ai-excellence'],
      ['Pricing page', '/pricing'],
    ],
    seoTitle: 'Automation Platform or Production Partner',
    seoDesc:
      'Automation multiplies assets you already have. It cannot originate the master. Where the handoff sits, what each layer costs, and a decision table.',
    faqs: [
      'Can a creative automation platform replace a production studio?',
      'What does creative automation actually do?',
      'Who makes the master creative?',
      'Do I need both a platform and a studio?',
      'When is automation alone enough?',
    ],
    cta: 'Talk about the originate layer',
  },
  {
    id: '19',
    week: 5,
    slot: 'A',
    brief: true,
    cluster: 'Buying models',
    contentType: 'Money page',
    readerStage: 'budget-holder',
    slug: 'china-or-india-for-creative-production',
    h1: 'China or India for creative production: an honest comparison',
    query: 'china vs india offshore creative production',
    secondary: [
      'offshore creative production comparison',
      'china vs india design outsourcing',
      'where to offshore creative work',
    ],
    verdict:
      'VACANT. Two of the top results are IT-outsourcing articles from the CIO and Computerworld era',
    words: 3200,
    angle:
      'The China-side case, argued by an operator that also runs Philippines operations and can therefore concede where India wins. Regions, not companies. Conceding first is what makes the rest credible.',
    mustInclude: [
      'An honest comparison table: cost, English fluency, time zones, talent pool scale, physical studio capacity, category proximity, IP and data, platform fluency',
      'Where India genuinely wins, stated first',
      'Where China wins: studio capacity, consumer electronics and beauty and fashion supply-chain proximity, native Douyin (抖音), RedNote (小红书) and Tmall (天猫) fluency',
      'The data and IP question handled directly rather than dodged',
    ],
    doNot: [
      'Name a single vendor in either country. The comparison is regional.',
    ],
    stats: [
      'Talent pool and cost figures carry a source, a date and a method, or are cut',
      'Where no comparable figure exists for both regions, say so rather than comparing unlike numbers',
    ],
    assets: [
      'Comparison table: dimension, India, China, who wins and why',
      'Table: category proximity by vertical',
      'Checklist: the data and IP questions to ask either region',
    ],
    links: [
      ['Who we are', '/the-studio/who-we-are'],
      ['Agencies solutions page', '/solutions/agencies'],
      ['Pricing page', '/pricing'],
    ],
    seoTitle: 'China or India for Creative Production',
    seoDesc:
      'An honest regional comparison: cost, English fluency, studio capacity, category proximity, IP and data. Where India wins, stated first.',
    faqs: [
      'Is China or India better for creative production?',
      'Where does India win on creative outsourcing?',
      'What is China better at for creative production?',
      'How do IP and data rules differ?',
      'Which region suits high-volume ecommerce content?',
    ],
    cta: 'Talk to the studio',
  },
  {
    id: '20',
    week: 7,
    slot: 'C',
    brief: true,
    cluster: 'Buying models',
    contentType: 'Operations page',
    readerStage: 'budget-holder',
    slug: 'offshore-creative-production-china',
    h1: 'Offshore creative production in China: what it means in 2026',
    query: 'offshore creative production china',
    secondary: [
      'china creative outsourcing',
      'offshore design studio china',
      'china production partner models',
    ],
    verdict:
      'WEAK. The head term is held by India and Philippines coverage with no China facility story',
    words: 2600,
    angle:
      'Take the geographic long tail rather than the head term. Nobody holding this query has a China facility to describe.',
    mustInclude: [
      'What offshore production actually looks like in China in 2026',
      'The models available: dedicated team, project, platform',
      'The 40 percent savings figure that circulates in the category, quoted as a market claim and then examined',
      'Data, contracting and payment mechanics',
      'How to run a pilot',
    ],
    doNot: ['Name the source of the 40 percent claim, or any vendor.'],
    stats: [
      'The circulating 40 percent offshore savings figure is a market claim published as a percentage with no absolute figures and no sample size: label it as such, then examine what it excludes',
    ],
    assets: [
      'Table: the three engagement models, what you buy, what you manage',
      'Pilot plan: weeks, gates, what to measure',
      'Checklist: data, contracting and payment questions',
    ],
    links: [
      ['The studio', '/the-studio'],
      ['Pricing page', '/pricing'],
      ['Agencies solutions page', '/solutions/agencies'],
    ],
    seoTitle: 'Offshore Creative Production in China',
    seoDesc:
      'What offshore creative production in China looks like in 2026: the three engagement models, the 40 percent savings claim examined, and how to pilot.',
    faqs: [
      'What is offshore creative production in China?',
      'Does offshore production really save 40 percent?',
      'What engagement models are available?',
      'How does data and IP work with a China studio?',
      'How do I run a pilot before committing?',
    ],
    cta: 'Scope a pilot',
  },
  {
    id: '21',
    week: 6,
    slot: 'C',
    brief: true,
    cluster: 'Buying models',
    contentType: 'Money page',
    readerStage: 'budget-holder',
    slug: 'subscription-or-managed-production',
    h1: 'Subscription or managed production: the unit you are buying',
    query: 'design subscription vs production partner',
    secondary: [
      'design subscription at volume',
      'unlimited design subscription limits',
      'managed creative production model',
    ],
    verdict:
      'WEAK. Avoid the phrase "creative subscription vs production studio", which a January 2026 consumer product launch has polluted',
    words: 2700,
    angle:
      'The unit of purchase. A subscription prices access to designers. Production prices delivered assets. That one distinction decides which model fits, and no comparison page starts there.',
    mustInclude: [
      'A comparison of the two models on the axis of what you are buying, not on features',
      'Published subscription price bands quoted as a category range with the collection date',
      'The queue-and-capacity problem in subscriptions at volume',
      'Where a subscription is genuinely right',
      'The mid-market gap that opened during 2026 as subscription floors rose',
    ],
    doNot: [
      'Name a subscription provider or attribute a price to one.',
      'Use the phrase "creative subscription vs production studio" as a heading. The SERP for it is polluted.',
    ],
    stats: [
      'Managed design subscription monthly floors, roughly $6,000 to $15,000, dedicated tiers from roughly $30,000, category range with a September 2026 collection date, published pricing pages only',
      'The mid-market gap is stated as an arithmetic consequence of the floors, shown, not asserted',
    ],
    assets: [
      'Answer table: what you buy, how it is priced, what breaks at volume',
      'Table: published category bands, what each tier includes, collection date',
      'Decision table: volume, turnaround, origination need',
    ],
    links: [
      ['Pricing page', '/pricing'],
      ['Brands solutions page', '/solutions/brands'],
      ['Quotation calculator', '/pricing/calculator'],
    ],
    seoTitle: 'Subscription or Managed Production',
    seoDesc:
      'A subscription prices access to designers. Production prices delivered assets. What that distinction changes, and where each model actually fits.',
    faqs: [
      'What is the difference between a design subscription and a production partner?',
      'What am I actually buying with a design subscription?',
      'Do design subscriptions work at high volume?',
      'When is a subscription the right choice?',
      'What do subscription price bands look like in 2026?',
    ],
    cta: 'Get a market range for your volume',
  },
  {
    id: '22',
    week: 5,
    slot: 'C',
    brief: true,
    cluster: 'Buying models',
    contentType: 'Operations page',
    readerStage: 'procurement',
    slug: 'questions-to-ask-ai-production-partner',
    h1: 'Twelve questions to ask an AI-native production partner',
    query: 'how to evaluate an AI content production partner',
    secondary: [
      'ai production vendor questions',
      'ai content partner evaluation',
      'ai creative vendor due diligence',
    ],
    verdict: 'VACANT',
    words: 2600,
    angle:
      'A procurement instrument, not a sales page. Written so a buyer can score three vendors with it, including hubStudio, and including questions hubStudio has to answer carefully.',
    mustInclude: [
      'Twelve questions with, for each, what a good answer sounds like and what a weak one sounds like',
      'A scoring table the reader can copy',
      'Questions on model ownership, training data provenance, likeness rights, labeling and disclosure, capacity and surge, revision policy, physical capability, data residency, and who actually does the work',
    ],
    doNot: [
      'Turn any question into a hubStudio advantage. If a question is one hubStudio answers awkwardly, say so.',
    ],
    stats: [
      'Where a question references a regulation, cite the instrument, the issuing body and the effective date',
    ],
    assets: [
      'The twelve questions, each with a good answer and a weak answer',
      'Copyable scoring table, three vendor columns',
      'Table: question, why it matters, what a bad answer costs you later',
    ],
    links: [
      ['AI excellence page', '/the-studio/ai-excellence'],
      ['Contact page', '/contact'],
      ['Copyright and AI resource', '/resources/copyright-and-ai'],
    ],
    seoTitle: '12 Questions for an AI Production Partner',
    seoDesc:
      'A procurement instrument for scoring AI production vendors: twelve questions, what a good answer sounds like, and a scoring table you can copy.',
    faqs: [
      'How do I evaluate an AI content production partner?',
      'Who owns a custom-trained brand model?',
      'What should I ask about training data provenance?',
      'How do I check likeness rights on AI talent?',
      'What questions cover data residency?',
      'How do I compare three AI vendors fairly?',
    ],
    cta: 'Put us through the list',
  },

  // ---------------------------------------------------------------- CLUSTER 4
  {
    id: '23',
    week: 1,
    slot: 'C',
    brief: true,
    cluster: 'Rights',
    contentType: 'Operations page',
    readerStage: 'practitioner',
    slug: 'china-ai-labeling-rules-production-workflow',
    h1: 'China\'s AI labeling rules: what your production workflow has to do',
    query: 'china ai content labeling rules for brands',
    secondary: [
      'china ai labeling workflow',
      'cac ai labeling measures brands',
      'gb 45438-2025 production',
    ],
    verdict: 'Operational tail of a hard legal head',
    words: 2400,
    angle:
      'Law firms own the legal head term and will keep it. Nobody has written what a production workflow actually has to do: where each label attaches, and where it gets lost. This is production practice, not legal advice, and the page says so plainly.',
    mustInclude: [
      'A workflow diagram from generation through retouch, versioning, upload and archive, showing where each label attaches and where it can be lost',
      'What an asset handover pack has to contain',
      'The export-survives-download requirement and what it means for file formats',
      'The February 2026 enforcement figures, sourced',
      'A plain line that this describes production practice, not legal advice',
    ],
    doNot: [
      'Publish a fine figure. Penalties are not specified as a new schedule and enforcement runs through existing instruments.',
      'Write "requires" about the allocation of duties between brand, agency and tool vendor. Write "generally treated as". That allocation is law-firm interpretation, not an explicit regulator statement.',
      'Compete with a law firm on the legal head term.',
    ],
    stats: [
      'CAC Measures for Labeling of AI-Generated Synthetic Content, issued 14 March 2025 by CAC, MIIT, MPS and NRTA, effective 1 September 2025, with mandatory national standard GB 45438-2025 in force the same day',
      'Two label layers: explicit (visible mark, opening-frame mark on video, voice cue on audio) and implicit (metadata carrying content attribute, provider name or code, content ID)',
      'Users must proactively declare. Removing, altering, forging or concealing a label is prohibited, as is supplying tools to do so',
      'Distribution platforms verify metadata and add notices in three cases: confirmed, declared, suspected',
      'February 2026 enforcement figures, from the original release, with the date and the issuing body',
    ],
    assets: [
      'Workflow diagram: generation to archive, label attach and label loss points marked',
      'Table: pipeline stage, explicit label, implicit label, survives or lost',
      'Handover pack contents list',
    ],
    links: [
      ['Copyright and AI resource', '/resources/copyright-and-ai'],
      ['Douyin platform page', '/solutions/platforms/douyin'],
      ['AI excellence page', '/the-studio/ai-excellence'],
    ],
    seoTitle: 'China AI Labeling Rules for Production',
    seoDesc:
      'What China\'s AI labeling rules mean for a production workflow: where each label attaches, where it gets stripped, and what a handover pack must carry.',
    faqs: [
      'What do China\'s AI labeling rules require?',
      'What is the difference between an explicit and an implicit label?',
      'Where does an AI label get lost in a production pipeline?',
      'Who is responsible for labeling, the brand or the agency?',
      'What has to be in an asset handover pack?',
      'Does the label have to survive download?',
    ],
    cta: 'Talk about your pipeline',
  },
  {
    id: '24',
    week: 2,
    slot: 'C',
    brief: true,
    cluster: 'Rights',
    contentType: 'Operations page',
    readerStage: 'practitioner',
    slug: 'disclosure-audit-trail-per-asset',
    h1: 'The disclosure audit trail: what a pipeline records per asset',
    query: 'ai content disclosure audit trail production',
    secondary: [
      'ai asset provenance record',
      'ai content compliance record keeping',
      'what to log per ai generated asset',
    ],
    verdict: 'VACANT',
    words: 2000,
    angle:
      'The operational layer law firms omit. What a production workflow has to record, per asset, to survive a disclosure audit in any jurisdiction. hubStudio\'s own audit trail is the worked example.',
    mustInclude: [
      'The record schema: model and version, prompt, reference images and their rights status, human edits, approver, date, destination markets',
      'How it is stored and for how long',
      'Who can ask for it and when',
      'The three regimes it has to satisfy at once, China labeling, EU AI Act Article 50, US state disclosure laws, as a table of what each asks for',
      'hubStudio\'s own audit trail as the worked example',
      'A plain line that this describes production practice, not legal advice',
    ],
    doNot: [
      'Interpret any of the three regimes beyond what the instrument itself says. Cite the article, not a commentary.',
    ],
    stats: [
      'Each regime cited by instrument, issuing body and effective date',
      'The 90-day file retention figure is hubStudio policy: state it as policy, not as a legal requirement',
    ],
    assets: [
      'Record schema table: field, what it holds, why an auditor asks for it',
      'Table: the three regimes, what each asks for, what satisfies it',
      'The worked example: one asset, every field filled',
    ],
    links: [
      ['AI excellence page', '/the-studio/ai-excellence'],
      ['Copyright and AI resource', '/resources/copyright-and-ai'],
      ['AI image production', '/solutions/ai-production/image'],
    ],
    seoTitle: 'The AI Disclosure Audit Trail per Asset',
    seoDesc:
      'What a production pipeline records per asset to survive a disclosure audit: the record schema, retention, and the three regimes it has to satisfy.',
    faqs: [
      'What should be logged for every AI-generated asset?',
      'How long do provenance records need to be kept?',
      'Who can request an AI disclosure audit trail?',
      'Does the EU AI Act require a per-asset record?',
      'What does a complete provenance record look like?',
    ],
    cta: 'Talk about your pipeline',
  },
  {
    id: '25',
    week: 4,
    slot: 'C',
    brief: true,
    cluster: 'Rights',
    contentType: 'Operations page',
    readerStage: 'practitioner',
    slug: 'content-credentials-c2pa-in-production',
    h1: 'Content Credentials in a real pipeline: where C2PA survives and where it breaks',
    query: 'c2pa content credentials for brands',
    secondary: [
      'content credentials production workflow',
      'c2pa survives platform upload',
      'do content credentials survive social media',
    ],
    verdict: 'WEAK. Tool-side coverage only, thinly, no producer voice',
    words: 2200,
    angle:
      'The producer\'s view. Where credentials survive from capture through retouch, versioning and platform upload, and exactly where they get stripped. Tested, not assumed.',
    mustInclude: [
      'A stage-by-stage survival table: capture, ingest, retouch, export, DAM, platform upload, social re-encode, each marked survives, degrades or strips',
      'Which platforms preserve credentials today and which do not, tested rather than assumed',
      'What to do when they break',
      'An honest verdict on whether it is worth implementing now',
      'A plain line that this describes production practice, not legal advice',
    ],
    doNot: [
      'Assert a platform behavior that was not tested. Every row in the survival table states the test date and the file type used.',
    ],
    stats: [
      'Every survival table row carries a test date, the file type, and the tool or platform version',
      'Where a platform behavior could not be tested, mark it untested rather than inferring it',
    ],
    assets: [
      'Survival table: stage, survives, degrades or strips, test date, file type',
      'Table: platform, preserves credentials, tested on',
      'Decision box: implement now, implement later, or wait',
    ],
    links: [
      ['Glossary', '/resources/glossary'],
      ['Short video design service', '/services/design/short-video'],
      ['AI excellence page', '/the-studio/ai-excellence'],
    ],
    seoTitle: 'Where C2PA Survives in a Real Pipeline',
    seoDesc:
      'Content Credentials tested stage by stage: capture, retouch, export, DAM, platform upload. Where they survive, where they strip, and whether to adopt.',
    faqs: [
      'Do Content Credentials survive social media upload?',
      'At what point does C2PA metadata get stripped?',
      'Which platforms preserve Content Credentials?',
      'Is C2PA worth implementing in 2026?',
      'What do I do when credentials break mid-pipeline?',
    ],
    cta: 'Talk about your pipeline',
  },
  {
    id: '26',
    week: 3,
    slot: 'C',
    brief: true,
    cluster: 'Rights',
    contentType: 'Operations page',
    readerStage: 'procurement',
    slug: 'ai-brand-ambassadors-what-you-sign',
    h1: 'AI brand ambassadors: what you actually sign',
    query: 'ai avatar likeness rights talent release',
    secondary: [
      'digital human talent release',
      'ai ambassador contract clauses',
      'synthetic talent likeness agreement',
    ],
    verdict:
      'VACANT on the practical side. Law firms explain the risk, nobody publishes what to sign',
    words: 2300,
    angle:
      'The practical artifact. An annotated release structure from a studio that casts and captures the talent, rather than a risk explainer from someone who has never run a scan session.',
    mustInclude: [
      'The clause map: scope, term, territory, permitted uses, retraining rights, derivative rights, revocation, compensation model, sunset and deletion',
      'The difference between a scanned real person, a composite and a fully synthetic character, and how the paperwork changes',
      'What happens when the campaign ends and the model persists',
      'China labeling duties attaching to a digital human',
      'The plain statement that a lawyer signs the final document',
      'A plain line that this describes production practice, not legal advice',
    ],
    doNot: [
      'Publish a template that reads as a legal document ready to sign. It is a clause map and a checklist.',
    ],
    stats: [
      'China labeling duties cited to the instrument and its effective date',
      'Any market practice on compensation models is labeled as observed practice, with the sample and period, or cut',
    ],
    assets: [
      'Clause map table: clause, what it controls, what a weak version leaves open',
      'Table: scanned person, composite, fully synthetic, how the paperwork changes',
      'Sunset checklist: what happens to the model at campaign end',
    ],
    links: [
      ['AI video production', '/solutions/ai-production/video'],
      ['Copyright and AI resource', '/resources/copyright-and-ai'],
      ['AI excellence page', '/the-studio/ai-excellence'],
    ],
    seoTitle: 'AI Brand Ambassadors: What You Sign',
    seoDesc:
      'The clause map for an AI ambassador release: scope, term, retraining rights, revocation, sunset and deletion, and how synthetic talent changes it.',
    faqs: [
      'What goes in an AI avatar talent release?',
      'Do I need a release for a fully synthetic character?',
      'Can a model be retrained after the campaign ends?',
      'What happens to a digital human when the contract lapses?',
      'Does a digital human have to be labeled in China?',
    ],
    cta: 'Talk about casting and capture',
  },

  // ---------------------------------------------------------------- CLUSTER 5
  {
    id: '27',
    week: 1,
    slot: 'D',
    brief: true,
    cluster: 'Craft',
    contentType: 'Proof page',
    readerStage: 'practitioner',
    slug: 'shoot-it-or-generate-it',
    h1: 'Shoot it or generate it: the decision rule, asset by asset',
    query: 'when to shoot vs generate product images',
    secondary: [
      'ai generated vs photographed product images',
      'when to use ai product photography',
      'shoot or generate decision',
    ],
    verdict: 'VACANT',
    words: 2000,
    angle:
      'The rule an actual studio uses, published. Lead with the four conditions that force capture, not with a ratio: the conditions are what the reader can act on, and three of the four are written into marketplace rules and statutes rather than into model capability. CORRECTED AFTER RESEARCH, 2026-09-09: the site publishes "most catalogs run about 70 percent generated, 30 percent shot" on the ecommerce design service page, and separately frames 20/80 on the who-we-are page as a judgment about "the work". The 20/80 is NOT scoped to color variants and the AI image production page publishes no ratio at all. The two published ratios count different things, so do not present them as one metric at two scopes.',
    mustInclude: [
      'A decision table by asset type',
      'The four conditions that force capture: texture and material truth, regulated categories, talent, physical scale',
      'The conditions that favour generation',
      'What goes wrong in each direction',
      'The cost consequence of getting it wrong',
    ],
    doNot: ['Publish a hubStudio rate.'],
    stats: [
      'The 70/30 generated-to-shot mix on ecommerce and the 20/80 shoot-to-generate mix on variants are hubStudio delivery figures: state the method, the sample and the period on the page',
    ],
    assets: [
      'Decision table: asset type, shoot, generate, or hybrid, and why',
      'Table: the four conditions that force capture, with an example each',
      'Table: failure mode, what it looks like, what it costs',
    ],
    links: [
      ['Video production service', '/services/design/video-production'],
      ['AI image production', '/solutions/ai-production/image'],
      ['Ecommerce design service', '/services/design/ecommerce'],
    ],
    seoTitle: 'Shoot It or Generate It: The Decision Rule',
    seoDesc:
      'The rule a working studio uses, asset by asset: the four conditions that force capture, when generation wins, and what getting it wrong costs.',
    faqs: [
      'When should a product be photographed instead of generated?',
      'What can AI not generate convincingly yet?',
      'What is a good shot-to-generated ratio?',
      'Which categories require real photography?',
      'What goes wrong when you generate something you should have shot?',
    ],
    cta: 'Talk to the production team',
  },
  {
    id: '28',
    week: 3,
    slot: 'D',
    brief: true,
    cluster: 'Craft',
    contentType: 'Proof page',
    readerStage: 'procurement',
    slug: 'china-ecommerce-content-pack',
    h1: 'What a China ecommerce content pack contains, SKU by SKU',
    query: 'china ecommerce content pack deliverables',
    secondary: [
      'tmall content deliverables list',
      'china listing assets per sku',
      'ecommerce content handover contents',
    ],
    verdict: 'VACANT',
    words: 1600,
    angle:
      'The deliverable list, itemised, so a buyer can compare quotes on the same basis for once. Three quotes for "China ecommerce content" currently describe three different scopes and nobody notices until delivery.',
    mustInclude: [
      'The full manifest for one SKU across Tmall (天猫) and JD (京东)',
      'Naming conventions and file structure',
      'What a complete handover contains: source files, layered masters, metadata, provenance, retention terms',
      'The 90-day retention question',
      'A quote-comparison checklist',
    ],
    doNot: ['Publish a hubStudio rate.'],
    stats: [
      'The manifest counts trace to the spec pieces in cluster 1. Nothing enters this list that is not verified on a spec page.',
      'The 90-day file retention figure is hubStudio policy, stated as policy',
    ],
    assets: [
      'Manifest table: asset, platform, count, format, what it is for',
      'File structure and naming convention block',
      'Quote-comparison checklist, copyable',
    ],
    links: [
      ['Ecommerce design service', '/services/design/ecommerce'],
      ['Tmall platform page', '/solutions/platforms/tmall'],
      ['JD platform page', '/solutions/platforms/jd'],
    ],
    seoTitle: 'What a China Content Pack Contains',
    seoDesc:
      'The itemised manifest for one SKU across Tmall and JD, naming conventions, what a complete handover includes, and a quote-comparison checklist.',
    faqs: [
      'What is in a China ecommerce content pack?',
      'How many assets does one SKU need for Tmall and JD?',
      'Should a handover include layered source files?',
      'How long are production files retained?',
      'How do I compare two China content quotes?',
    ],
    cta: 'Get a like-for-like scope',
  },
  {
    id: '29',
    week: 5,
    slot: 'D',
    brief: true,
    cluster: 'Craft',
    contentType: 'Proof page',
    readerStage: 'budget-holder',
    slug: 'training-a-brand-model-that-stays-on-brand',
    h1: 'Training a brand model that stays on brand: 22 percent to 78 percent',
    query: 'custom brand model training aigc approval rate',
    secondary: [
      'train ai model on brand assets',
      'brand consistency ai generation',
      'custom model training for brands',
    ],
    verdict: 'WEAK',
    words: 1600,
    angle:
      'The internal approval rate as the honest metric for AI content quality, with hubStudio\'s own move from 22 to 78 percent as the case, method stated. Everyone else claims quality. A rate you can audit is a different kind of claim.',
    mustInclude: [
      'What internal approval rate measures and why it beats any quality claim',
      'The five-stage pipeline',
      'What training data a brand model needs and what it must never contain',
      'The 3 to 6 week training window',
      'Review gates',
      'Who owns the trained model at the end',
    ],
    doNot: ['Publish a hubStudio rate for model training.'],
    stats: [
      'The 22 percent to 78 percent internal approval rate is hubStudio delivery data: the page must state what an approval is, who approves, the sample size, and the period over which the move happened. Without that method statement the figure does not go on the page.',
      'The 3 to 6 week training window is stated as observed range across engagements, with the sample',
    ],
    assets: [
      'Table: the five stages, what happens, what gate closes it',
      'Table: training data, required, optional, never',
      'Chart: approval rate over the training period, method noted on the chart',
    ],
    links: [
      ['AI excellence page', '/the-studio/ai-excellence'],
      ['hub4you platform', '/hub4you'],
      ['AI image production', '/solutions/ai-production/image'],
    ],
    seoTitle: 'Training a Brand Model That Stays on Brand',
    seoDesc:
      'Internal approval rate is the honest metric for AI content quality. The five-stage pipeline, the training data rules, and a move from 22 to 78 percent.',
    faqs: [
      'What is an internal approval rate?',
      'How long does it take to train a custom brand model?',
      'What training data does a brand model need?',
      'What must never go into brand model training data?',
      'Who owns the trained model at the end?',
    ],
    cta: 'Talk about a brand model',
    notes:
      'Needs the internal approval-rate method written down and cleared before drafting. Start in week 3.',
  },
  {
    id: '30',
    week: 4,
    slot: 'D',
    brief: true,
    cluster: 'Craft',
    contentType: 'Proof page',
    readerStage: 'practitioner',
    slug: 'singles-day-618-production-calendar',
    h1: 'The 11.11 and 618 production calendar, counted backwards',
    query: 'singles day 618 content production timeline',
    secondary: [
      'double 11 content deadline',
      '618 campaign production timeline',
      'china sale event asset lock dates',
    ],
    verdict:
      'VACANT. Results drift to Western event production and encyclopaedia entries',
    words: 1900,
    angle:
      'A real reverse-engineered calendar with lock dates, asset counts and approval gates counted backwards from the sale date. Every ranking page explains what Singles Day is. None says when your assets have to be locked.',
    mustInclude: [
      'The full timeline as a table, week by week, from T minus 16 to launch',
      'The platform milestones: registration, pre-sale, warm-up, main sale, restock',
      'Asset counts at each gate',
      'What has to be locked before Chinese New Year in a 618 (六一八) cycle',
      'The two failure modes, late approval and late reshoot, and what they cost',
    ],
    stats: [
      'Platform milestone dates come from the platform seller announcements only, with the year stated, because they move annually',
      'Asset counts at each gate trace to the China variant matrix piece',
    ],
    assets: [
      'The calendar as one table: week, milestone, what locks, asset count',
      'Table: failure mode, when it bites, what it costs',
      'Countdown checklist, copyable',
    ],
    links: [
      ['Tmall platform page', '/solutions/platforms/tmall'],
      ['Retailers solutions page', '/solutions/retailers'],
      ['Ecommerce design service', '/services/design/ecommerce'],
    ],
    seoTitle: 'The 11.11 and 618 Production Calendar',
    seoDesc:
      'A reverse-engineered production calendar for Singles Day and 618: lock dates, asset counts, approval gates, and the two failure modes that cost most.',
    faqs: [
      'When do Singles Day assets have to be locked?',
      'How long before 618 should production start?',
      'What are the Tmall pre-sale milestones?',
      'How does Chinese New Year affect a 618 cycle?',
      'What happens if creative approval slips?',
    ],
    cta: 'Plan the cycle with us',
  },

  // ----------------------------------------------- BATCH TWO: calendar rows
  // Briefed in month two, per Part 3 of the search spec.
  { id: '31', week: 6, slot: 'D', brief: false, cluster: 'China specs', slug: 'amazon-tmall-jd-one-product-three-listings', h1: 'Amazon, Tmall, JD: one product, three listing builds' },
  { id: '32', week: 7, slot: 'D', brief: false, cluster: 'China specs', slug: 'meta-tiktok-against-douyin-rednote', h1: 'Meta and TikTok against Douyin and RedNote: the same campaign, twice' },
  { id: '33', week: 9, slot: 'A', brief: false, cluster: 'Research', slug: 'real-cost-of-brand-content-2026', h1: 'The Real Cost of Brand Content 2026: the benchmark, ungated' },
  { id: '34', week: 9, slot: 'B', brief: false, cluster: 'Playbook', slug: 'beauty-content-production-china', h1: 'Beauty content production in China: the category playbook' },
  { id: '35', week: 9, slot: 'C', brief: false, cluster: 'Buying models', slug: 'agency-white-label-question', h1: 'The agency white-label question: NDA, contact rules, margin per asset' },
  { id: '36', week: 9, slot: 'D', brief: false, cluster: 'Data', slug: 'how-many-variants-a-china-launch-needs', h1: 'How many variants a China launch actually needs' },
  { id: '37', week: 10, slot: 'A', brief: false, cluster: 'Buying models', slug: 'procurement-guide-buying-ai-content-production', h1: 'Procurement\'s guide to buying AI content production' },
  { id: '38', week: 10, slot: 'B', brief: false, cluster: 'Playbook', slug: 'automotive-content-without-shipping-a-car', h1: 'Automotive content without shipping a car' },
  { id: '39', week: 10, slot: 'C', brief: false, cluster: 'Operations', slug: 'turnaround-days-not-weeks', h1: 'Turnaround: what days not weeks means, stage by stage' },
  { id: '40', week: 10, slot: 'D', brief: false, cluster: 'Craft', slug: 'the-2026-model-roster', h1: 'The 2026 model roster: which model for which asset' },
  { id: '41', week: 11, slot: 'A', brief: false, cluster: 'Operations', slug: 'what-a-48-hour-binding-proposal-contains', h1: 'What a 48-hour binding proposal contains' },
  { id: '42', week: 11, slot: 'B', brief: false, cluster: 'Playbook', slug: 'consumer-electronics-launch-content', h1: 'Consumer electronics launch content: the six-week build' },
  { id: '43', week: 11, slot: 'C', brief: false, cluster: 'Craft', slug: 'lip-sync-across-47-languages', h1: 'Lip sync across 47 languages: what breaks and what it costs' },
  { id: '44', week: 11, slot: 'D', brief: false, cluster: 'Operations', slug: 'transcreation-as-a-production-line', h1: 'Transcreation as a production line, not a translation service' },
  { id: '45', week: 12, slot: 'A', brief: false, cluster: 'Cost', slug: 'digital-humans-in-china', h1: 'Digital humans in China: build cost, run cost, labeling duties' },
  { id: '46', week: 12, slot: 'B', brief: false, cluster: 'Playbook', slug: 'running-a-tmall-flagship-content', h1: 'Running a Tmall flagship\'s content, month by month' },
  { id: '47', week: 12, slot: 'C', brief: false, cluster: 'Operations', slug: 'retouch-at-volume-qa-pipeline', h1: 'Retouch at volume: the QA pipeline behind a 78 percent approval rate' },
  { id: '48', week: 12, slot: 'D', brief: false, cluster: 'Proof', slug: 'hisense-rebuilt-self-serve-platform', h1: 'HiSense rebuilt: eight weeks to a self-serve content platform' },
];
