import { chromium } from 'playwright';
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1280, height: 900 } });
await p.goto('http://127.0.0.1:4321/', { waitUntil: 'networkidle' });
await p.waitForTimeout(400);
await p.screenshot({ path: 'scripts/_v-header.png', clip: { x: 0, y: 0, width: 1280, height: 90 } });
await p.evaluate(() => window.scrollTo(0, document.body.scrollHeight));
await p.waitForTimeout(400);
const h = await p.evaluate(() => document.body.scrollHeight);
await p.screenshot({ path: 'scripts/_v-footer.png', clip: { x: 0, y: h - 480, width: 1280, height: 480 } });
await b.close();
console.log('done');
